# Generated by Django 5.0 on 2023-12-12 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos_mensuales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_mensuales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos_mensuales.pagosmensuales')),
            ],
        ),
    ]
