# Generated by Django 5.0 on 2023-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_Pago',
            fields=[
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Crear_Pago',
            },
        ),
    ]
