# Generated by Django 5.0 on 2023-12-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('clientes', '0004_cliente_nombre_producto'),
        ('crear_pago', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosMensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_mensuales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('opcion1', 'Cancelado'), ('opcion2', 'Por pagar')], default='opcion2', max_length=20)),
                ('total_cobrar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('crear_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crear_pago.crear_pago')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
            options={
                'db_table': 'PagosMensuales',
            },
        ),
    ]
