# Generated by Django 5.0 on 2023-12-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosMensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_mensuales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('opcion1', 'Cancelado'), ('opcion2', 'Por pagar')], default='opcion1', max_length=20)),
                ('total_cobrar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'PagosMensuales',
            },
        ),
    ]
