# Generated by Django 5.0 on 2023-12-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre_producto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
