# Generated by Django 5.0 on 2023-12-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('productos', '0002_alter_producto_cantidad_alter_producto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='meses_diferidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
    ]
