# Generated by Django 5.0 on 2023-12-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_id_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
