# Generated by Django 5.0 on 2023-12-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_table'),
        ('productos', '0002_alter_producto_cantidad_alter_producto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
